const express = require('express');
const cors = require("cors");
const app = express();
const db = require('./models');
const bodyParser = require('body-parser');
const corsOptions = require('./config/corsOptions') 

const port = process.env.PORT || 3001;
const Role = db.role;
app.use(bodyParser.json());
app.use(express.static('resources'));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors(corsOptions));

// routers   
const customerRouter = require('./routes/customer');
app.use('/', customerRouter);

const registerRouter = require('./routes/register');
app.use('/', registerRouter);

const alameiaRouter = require('./routes/alameia');
app.use('/', alameiaRouter);

const haramainRouter = require('./routes/haramain');
app.use('/', haramainRouter);

const ewaaaRouter = require('./routes/ewaaa');
app.use('/', ewaaaRouter);

const ewaabRouter = require('./routes/ewaab');
app.use('/', ewaabRouter);

const usersRouter = require('./routes/users');
app.use('/', usersRouter);

app.use('/auth', require('./routes/authRoutes'));

/////////////////////////////////// Buildings
const sawady2Router = require('./routes/sawady2');
app.use('/', sawady2Router);
const batawy1Router = require('./routes/batawy1');
app.use('/', batawy1Router);
const safaMashaerRouter = require('./routes/safamashaer');
app.use('/', safaMashaerRouter);
const matrafyRouter = require('./routes/matrafy');
app.use('/', matrafyRouter);
const saqafRouter = require('./routes/saqaf');
app.use('/', saqafRouter);
const fedaRouter = require('./routes/feda');
app.use('/', fedaRouter);
const sawady1Router = require('./routes/sawady1');
app.use('/', sawady1Router);
const rahmaneyaRouter = require('./routes/rahmaneya');
app.use('/', rahmaneyaRouter);
const elsalamRouter = require('./routes/elsalam');
app.use('/', elsalamRouter);
const elfatehRouter = require('./routes/elfateh');
app.use('/', elfatehRouter);
const paradiseRouter = require('./routes/paradise');
app.use('/', paradiseRouter);
const batawy2Router = require('./routes/batawy2');
app.use('/', batawy2Router);
const hemyaniRouter = require('./routes/hemyani');
app.use('/', hemyaniRouter);
const nefeayRouter = require('./routes/nefeay');
app.use('/', nefeayRouter);
const morgan1NaseemRouter = require('./routes/morgan1naseem');
app.use('/', morgan1NaseemRouter);
const morgan2BathaaRouter = require('./routes/morgan2bathaa');
app.use('/', morgan2BathaaRouter);
const waqfRouter = require('./routes/waqf');
app.use('/', waqfRouter);
/////////////////////////////////// Buildings
///////////////////////////////////////////////////////////// Projects
//////////////////////////////////////////// Alameia
const abrajkudai = require('./routes/alameiaProjects/AbrajKudai')
app.use('/', abrajkudai)
const alameiaAhla = require('./routes/alameiaProjects/AlameiaAhla')
app.use('/', alameiaAhla)
const alameiaConsums = require('./routes/alameiaProjects/alameiaconsums')
app.use('/', alameiaConsums)
const alameiaMaintainence = require('./routes/alameiaProjects/alameiamaintainence')
app.use('/', alameiaMaintainence)
const campsEmployee = require('./routes/alameiaProjects/CampsEmployee')
app.use('/', campsEmployee)
const centralStation = require('./routes/alameiaProjects/centralStation')
app.use('/', centralStation)
const enma = require('./routes/alameiaProjects/Enma')
app.use('/', enma)
const eamarMaterial = require('./routes/alameiaProjects/EamarMaterial')
app.use('/', eamarMaterial)
const firstRingRoad = require('./routes/alameiaProjects/FirstRingRoad')
app.use('/', firstRingRoad)
const hrServices = require('./routes/alameiaProjects/Hrservices')
app.use('/', hrServices)
const iblik = require('./routes/alameiaProjects/Iblik')
app.use('/', iblik)
const infraStracture = require('./routes/alameiaProjects/InfraStractureHaram')
app.use('/', infraStracture)
const marwa = require('./routes/alameiaProjects/Marwa')
app.use('/', marwa)
const masar = require('./routes/alameiaProjects/Masar')
app.use('/', masar)
const mataf = require('./routes/alameiaProjects/Mataf')
app.use('/', mataf)
const najm = require('./routes/alameiaProjects/Najm')
app.use('/', najm)
const sahat = require('./routes/alameiaProjects/Sahat')
app.use('/', sahat)
const salama = require('./routes/alameiaProjects/Salama')
app.use('/', salama)
const securityBuildings = require('./routes/alameiaProjects/SecurityBuildings')
app.use('/', securityBuildings)
const serviceBuildings = require('./routes/alameiaProjects/ServiceBuildings')
app.use('/', serviceBuildings)
const serviceBuildingsSec16 = require('./routes/alameiaProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16)
const shameya = require('./routes/alameiaProjects/Shameya')
app.use('/', shameya)
const trainConcrete = require('./routes/alameiaProjects/TrainConcrete')
app.use('/', trainConcrete)
const warehouseFrr = require('./routes/alameiaProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr)
const warehouseMataf = require('./routes/alameiaProjects/WarehouseMataf')
app.use('/', warehouseMataf)
const warehouseShameya = require('./routes/alameiaProjects/WarehouseShameya')
app.use('/', warehouseShameya)
const zakzoki = require('./routes/alameiaProjects/ZakzokiFireFighting')
app.use('/', zakzoki)
const metalsaudidecoration = require('./routes/alameiaProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration)
const invoiceReport = require('./routes/alameiaProjects/InvoiceReport')
app.use('/', invoiceReport)

//////////////////////////////////////////// Alameia
//////////////////////////////////////////// Ewaaa
const abrajkudai1 = require('./routes/ewaaaProjects/AbrajKudai')
app.use('/', abrajkudai1)
const alameiaAhla1 = require('./routes/ewaaaProjects/AlameiaAhla')
app.use('/', alameiaAhla1)
const alameiaConsums1 = require('./routes/ewaaaProjects/alameiaconsums')
app.use('/', alameiaConsums1)
const alameiaMaintainence1 = require('./routes/ewaaaProjects/alameiamaintainence')
app.use('/', alameiaMaintainence1)
const campsEmployee1 = require('./routes/ewaaaProjects/CampsEmployee')
app.use('/', campsEmployee1)
const centralStation1 = require('./routes/ewaaaProjects/centralStation')
app.use('/', centralStation1)
const enma1 = require('./routes/ewaaaProjects/Enma')
app.use('/', enma1)
const eamarMaterial1 = require('./routes/ewaaaProjects/EamarMaterial')
app.use('/', eamarMaterial1)
const firstRingRoad1 = require('./routes/ewaaaProjects/FirstRingRoad')
app.use('/', firstRingRoad1)
const hrServices1 = require('./routes/ewaaaProjects/Hrservices')
app.use('/', hrServices1)
const iblik1 = require('./routes/ewaaaProjects/Iblik')
app.use('/', iblik1)
const infraStracture1 = require('./routes/ewaaaProjects/InfraStractureHaram')
app.use('/', infraStracture1)
const marwa1 = require('./routes/ewaaaProjects/Marwa')
app.use('/', marwa1)
const masar1 = require('./routes/ewaaaProjects/Masar')
app.use('/', masar1)
const mataf1 = require('./routes/ewaaaProjects/Mataf')
app.use('/', mataf1)
const najm1 = require('./routes/ewaaaProjects/Najm')
app.use('/', najm1)
const sahat1 = require('./routes/ewaaaProjects/Sahat')
app.use('/', sahat1)
const salama1 = require('./routes/ewaaaProjects/Salama')
app.use('/', salama1)
const securityBuildings1 = require('./routes/ewaaaProjects/SecurityBuildings')
app.use('/', securityBuildings1)
const serviceBuildings1 = require('./routes/ewaaaProjects/ServiceBuildings')
app.use('/', serviceBuildings1)
const serviceBuildingsSec161 = require('./routes/ewaaaProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec161)
const shameya1 = require('./routes/ewaaaProjects/Shameya')
app.use('/', shameya1)
const trainConcrete1 = require('./routes/ewaaaProjects/TrainConcrete')
app.use('/', trainConcrete1)
const warehouseFrr1 = require('./routes/ewaaaProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr1)
const warehouseMataf1 = require('./routes/ewaaaProjects/WarehouseMataf')
app.use('/', warehouseMataf1)
const warehouseShameya1 = require('./routes/ewaaaProjects/WarehouseShameya')
app.use('/', warehouseShameya1)
const zakzoki1 = require('./routes/ewaaaProjects/ZakzokiFireFighting')
app.use('/', zakzoki1)
const metalsaudidecoration1 = require('./routes/ewaaaProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration1)
const invoiceReport1 = require('./routes/ewaaaProjects/InvoiceReport')
app.use('/', invoiceReport1)
//////////////////////////////////////////// Ewaaa
//////////////////////////////////////////// Ewaab
const abrajkudai2 = require('./routes/ewaabProjects/AbrajKudai')
app.use('/', abrajkudai2)
const alameiaAhla2 = require('./routes/ewaabProjects/AlameiaAhla')
app.use('/', alameiaAhla2)
const alameiaConsums2 = require('./routes/ewaabProjects/alameiaconsums')
app.use('/', alameiaConsums2)
const alameiaMaintainence2 = require('./routes/ewaabProjects/alameiamaintainence')
app.use('/', alameiaMaintainence2)
const campsEmployee2 = require('./routes/ewaabProjects/CampsEmployee')
app.use('/', campsEmployee2)
const centralStation2 = require('./routes/ewaabProjects/centralStation')
app.use('/', centralStation2)
const enma2 = require('./routes/ewaabProjects/Enma')
app.use('/', enma2)
const eamarMaterial2 = require('./routes/ewaabProjects/EamarMaterial')
app.use('/', eamarMaterial2)
const firstRingRoad2 = require('./routes/ewaabProjects/FirstRingRoad')
app.use('/', firstRingRoad2)
const hrServices2 = require('./routes/ewaabProjects/Hrservices')
app.use('/', hrServices2)
const iblik2 = require('./routes/ewaabProjects/Iblik')
app.use('/', iblik2)
const infraStracture2 = require('./routes/ewaabProjects/InfraStractureHaram')
app.use('/', infraStracture2)
const marwa2 = require('./routes/ewaabProjects/Marwa')
app.use('/', marwa2)
const masar2 = require('./routes/ewaabProjects/Masar')
app.use('/', masar2)
const mataf2 = require('./routes/ewaabProjects/Mataf')
app.use('/', mataf2)
const najm2 = require('./routes/ewaabProjects/Najm')
app.use('/', najm2)
const sahat2 = require('./routes/ewaabProjects/Sahat')
app.use('/', sahat2)
const salama2 = require('./routes/ewaabProjects/Salama')
app.use('/', salama2)
const securityBuildings2 = require('./routes/ewaabProjects/SecurityBuildings')
app.use('/', securityBuildings2)
const serviceBuildings2 = require('./routes/ewaabProjects/ServiceBuildings')
app.use('/', serviceBuildings2)
const serviceBuildingsSec162 = require('./routes/ewaabProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec162)
const shameya2 = require('./routes/ewaabProjects/Shameya')
app.use('/', shameya2)
const trainConcrete2 = require('./routes/ewaabProjects/TrainConcrete')
app.use('/', trainConcrete2)
const warehouseFrr2 = require('./routes/ewaabProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr2)
const warehouseMataf2 = require('./routes/ewaabProjects/WarehouseMataf')
app.use('/', warehouseMataf2)
const warehouseShameya2 = require('./routes/ewaabProjects/WarehouseShameya')
app.use('/', warehouseShameya2)
const zakzoki2 = require('./routes/ewaabProjects/ZakzokiFireFighting')
app.use('/', zakzoki2)
const metalsaudidecoration2 = require('./routes/ewaabProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration2)
const invoiceReport2 = require('./routes/ewaabProjects/InvoiceReport')
app.use('/', invoiceReport2)
//////////////////////////////////////////// Ewaab
//////////////////////////////////////////// Haramain
const abrajkudai3 = require('./routes/haramainProjects/AbrajKudai')
app.use('/', abrajkudai3)
const alameiaAhla3 = require('./routes/haramainProjects/AlameiaAhla')
app.use('/', alameiaAhla3)
const alameiaConsums3 = require('./routes/haramainProjects/alameiaconsums')
app.use('/', alameiaConsums3)
const alameiaMaintainence3 = require('./routes/haramainProjects/alameiamaintainence')
app.use('/', alameiaMaintainence3)
const campsEmployee3 = require('./routes/haramainProjects/CampsEmployee')
app.use('/', campsEmployee3)
const centralStation3 = require('./routes/haramainProjects/centralStation')
app.use('/', centralStation3)
const enma3 = require('./routes/haramainProjects/Enma')
app.use('/', enma3)
const eamarMaterial3 = require('./routes/haramainProjects/EamarMaterial')
app.use('/', eamarMaterial3)
const firstRingRoad3 = require('./routes/haramainProjects/FirstRingRoad')
app.use('/', firstRingRoad3)
const hrServices3 = require('./routes/haramainProjects/Hrservices')
app.use('/', hrServices3)
const iblik3 = require('./routes/haramainProjects/Iblik')
app.use('/', iblik3)
const infraStracture3 = require('./routes/haramainProjects/InfraStractureHaram')
app.use('/', infraStracture3)
const marwa3 = require('./routes/haramainProjects/Marwa')
app.use('/', marwa3)
const masar3 = require('./routes/haramainProjects/Masar')
app.use('/', masar3)
const mataf3 = require('./routes/haramainProjects/Mataf')
app.use('/', mataf3)
const najm3 = require('./routes/haramainProjects/Najm')
app.use('/', najm3)
const sahat3 = require('./routes/haramainProjects/Sahat')
app.use('/', sahat3)
const salama3 = require('./routes/haramainProjects/Salama')
app.use('/', salama3)
const securityBuildings3 = require('./routes/haramainProjects/SecurityBuildings')
app.use('/', securityBuildings3)
const serviceBuildings3 = require('./routes/haramainProjects/ServiceBuildings')
app.use('/', serviceBuildings3)
const serviceBuildingsSec163 = require('./routes/haramainProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec163)
const shameya3 = require('./routes/haramainProjects/Shameya')
app.use('/', shameya3)
const trainConcrete3 = require('./routes/haramainProjects/TrainConcrete')
app.use('/', trainConcrete3)
const warehouseFrr3 = require('./routes/haramainProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr3)
const warehouseMataf3 = require('./routes/haramainProjects/WarehouseMataf')
app.use('/', warehouseMataf3)
const warehouseShameya3 = require('./routes/haramainProjects/WarehouseShameya')
app.use('/', warehouseShameya3)
const zakzoki3 = require('./routes/haramainProjects/ZakzokiFireFighting')
app.use('/', zakzoki3)
const metalsaudidecoration3 = require('./routes/haramainProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration3)
const invoiceReport3 = require('./routes/haramainProjects/InvoiceReport')
app.use('/', invoiceReport3)
//////////////////////////////////////////// Haramain  
//////////////////////////////////////////// Sawady1
const abrajkudai31 = require('./routes/sawady1Projects/AbrajKudai')
app.use('/', abrajkudai31)
const alameiaAhla31 = require('./routes/sawady1Projects/AlameiaAhla')
app.use('/', alameiaAhla31)
const alameiaConsums31 = require('./routes/sawady1Projects/alameiaconsums')
app.use('/', alameiaConsums31)
const alameiaMaintainence31 = require('./routes/sawady1Projects/alameiamaintainence')
app.use('/', alameiaMaintainence31)
const campsEmployee31 = require('./routes/sawady1Projects/CampsEmployee')
app.use('/', campsEmployee31)
const centralStation31 = require('./routes/sawady1Projects/centralStation')
app.use('/', centralStation31)
const enma31 = require('./routes/sawady1Projects/Enma')
app.use('/', enma31)
const eamarMaterial31 = require('./routes/sawady1Projects/EamarMaterial')
app.use('/', eamarMaterial31)
const firstRingRoad31 = require('./routes/sawady1Projects/FirstRingRoad')
app.use('/', firstRingRoad31)
const hrServices31 = require('./routes/sawady1Projects/Hrservices')
app.use('/', hrServices31)
const iblik31 = require('./routes/sawady1Projects/Iblik')
app.use('/', iblik31)
const infraStracture31 = require('./routes/sawady1Projects/InfraStractureHaram')
app.use('/', infraStracture31)
const marwa31 = require('./routes/sawady1Projects/Marwa')
app.use('/', marwa31)
const masar31 = require('./routes/sawady1Projects/Masar')
app.use('/', masar31)
const mataf31 = require('./routes/sawady1Projects/Mataf')
app.use('/', mataf31)
const najm31 = require('./routes/sawady1Projects/Najm')
app.use('/', najm31)
const sahat31 = require('./routes/sawady1Projects/Sahat')
app.use('/', sahat31)
const salama31 = require('./routes/sawady1Projects/Salama')
app.use('/', salama31)
const securityBuildings31 = require('./routes/sawady1Projects/SecurityBuildings')
app.use('/', securityBuildings31)
const serviceBuildings31 = require('./routes/sawady1Projects/ServiceBuildings')
app.use('/', serviceBuildings31)
const serviceBuildingsSec1631 = require('./routes/sawady1Projects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1631)
const shameya31 = require('./routes/sawady1Projects/Shameya')
app.use('/', shameya31)
const trainConcrete31 = require('./routes/sawady1Projects/TrainConcrete')
app.use('/', trainConcrete31)
const warehouseFrr31 = require('./routes/sawady1Projects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr31)
const warehouseMataf31 = require('./routes/sawady1Projects/WarehouseMataf')
app.use('/', warehouseMataf31)
const warehouseShameya31 = require('./routes/sawady1Projects/WarehouseShameya')
app.use('/', warehouseShameya31)
const zakzoki31 = require('./routes/sawady1Projects/ZakzokiFireFighting')
app.use('/', zakzoki31)
const metalsaudidecoration31 = require('./routes/sawady1Projects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration31)
const invoiceReport31 = require('./routes/sawady1Projects/InvoiceReport')
app.use('/', invoiceReport31)
//////////////////////////////////////////// Sawady1  
//////////////////////////////////////////// Sawady2
const abrajkudai32 = require('./routes/sawady2Projects/AbrajKudai')
app.use('/', abrajkudai32)
const alameiaAhla32 = require('./routes/sawady2Projects/AlameiaAhla')
app.use('/', alameiaAhla32)
const alameiaConsums32 = require('./routes/sawady2Projects/alameiaconsums')
app.use('/', alameiaConsums32)
const alameiaMaintainence32 = require('./routes/sawady2Projects/alameiamaintainence')
app.use('/', alameiaMaintainence32)
const campsEmployee32 = require('./routes/sawady2Projects/CampsEmployee')
app.use('/', campsEmployee32)
const centralStation32 = require('./routes/sawady2Projects/centralStation')
app.use('/', centralStation32)
const enma32 = require('./routes/sawady2Projects/Enma')
app.use('/', enma32)
const eamarMaterial32 = require('./routes/sawady2Projects/EamarMaterial')
app.use('/', eamarMaterial32)
const firstRingRoad32 = require('./routes/sawady2Projects/FirstRingRoad')
app.use('/', firstRingRoad32)
const hrServices32 = require('./routes/sawady2Projects/Hrservices')
app.use('/', hrServices32)
const iblik32 = require('./routes/sawady2Projects/Iblik')
app.use('/', iblik32)
const infraStracture32 = require('./routes/sawady2Projects/InfraStractureHaram')
app.use('/', infraStracture32)
const marwa32 = require('./routes/sawady2Projects/Marwa')
app.use('/', marwa32)
const masar32 = require('./routes/sawady2Projects/Masar')
app.use('/', masar32)
const mataf32 = require('./routes/sawady2Projects/Mataf')
app.use('/', mataf32)
const najm32 = require('./routes/sawady2Projects/Najm')
app.use('/', najm32)
const sahat32 = require('./routes/sawady2Projects/Sahat')
app.use('/', sahat32)
const salama32 = require('./routes/sawady2Projects/Salama')
app.use('/', salama32)
const securityBuildings32 = require('./routes/sawady2Projects/SecurityBuildings')
app.use('/', securityBuildings32)
const serviceBuildings32 = require('./routes/sawady2Projects/ServiceBuildings')
app.use('/', serviceBuildings32)
const serviceBuildingsSec1632 = require('./routes/sawady2Projects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1632)
const shameya32 = require('./routes/sawady2Projects/Shameya')
app.use('/', shameya32)
const trainConcrete32 = require('./routes/sawady2Projects/TrainConcrete')
app.use('/', trainConcrete32)
const warehouseFrr32 = require('./routes/sawady2Projects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr32)
const warehouseMataf32 = require('./routes/sawady2Projects/WarehouseMataf')
app.use('/', warehouseMataf32)
const warehouseShameya32 = require('./routes/sawady2Projects/WarehouseShameya')
app.use('/', warehouseShameya32)
const zakzoki32 = require('./routes/sawady2Projects/ZakzokiFireFighting')
app.use('/', zakzoki32)
const metalsaudidecoration32 = require('./routes/sawady2Projects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration32)
const invoiceReport32 = require('./routes/sawady2Projects/InvoiceReport')
app.use('/', invoiceReport32)
//////////////////////////////////////////// Sawady2 
//////////////////////////////////////////// Batawy1
const abrajkudai33 = require('./routes/batawy1Projects/AbrajKudai')
app.use('/', abrajkudai33)
const alameiaAhla33 = require('./routes/batawy1Projects/AlameiaAhla')
app.use('/', alameiaAhla33)
const alameiaConsums33 = require('./routes/batawy1Projects/alameiaconsums')
app.use('/', alameiaConsums33)
const alameiaMaintainence33 = require('./routes/batawy1Projects/alameiamaintainence')
app.use('/', alameiaMaintainence33)
const campsEmployee33 = require('./routes/batawy1Projects/CampsEmployee')
app.use('/', campsEmployee33)
const centralStation33 = require('./routes/batawy1Projects/centralStation')
app.use('/', centralStation33)
const enma33 = require('./routes/batawy1Projects/Enma')
app.use('/', enma33)
const eamarMaterial33 = require('./routes/batawy1Projects/EamarMaterial')
app.use('/', eamarMaterial33)
const firstRingRoad33 = require('./routes/batawy1Projects/FirstRingRoad')
app.use('/', firstRingRoad33)
const hrServices33 = require('./routes/batawy1Projects/Hrservices')
app.use('/', hrServices33)
const iblik33 = require('./routes/batawy1Projects/Iblik')
app.use('/', iblik33)
const infraStracture33 = require('./routes/batawy1Projects/InfraStractureHaram')
app.use('/', infraStracture33)
const marwa33 = require('./routes/batawy1Projects/Marwa')
app.use('/', marwa33)
const masar33 = require('./routes/batawy1Projects/Masar')
app.use('/', masar33)
const mataf33 = require('./routes/batawy1Projects/Mataf')
app.use('/', mataf33)
const najm33 = require('./routes/batawy1Projects/Najm')
app.use('/', najm33)
const sahat33 = require('./routes/batawy1Projects/Sahat')
app.use('/', sahat33)
const salama33 = require('./routes/batawy1Projects/Salama')
app.use('/', salama33)
const securityBuildings33 = require('./routes/batawy1Projects/SecurityBuildings')
app.use('/', securityBuildings33)
const serviceBuildings33 = require('./routes/batawy1Projects/ServiceBuildings')
app.use('/', serviceBuildings33)
const serviceBuildingsSec1633 = require('./routes/batawy1Projects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1633)
const shameya33 = require('./routes/batawy1Projects/Shameya')
app.use('/', shameya33)
const trainConcrete33 = require('./routes/batawy1Projects/TrainConcrete')
app.use('/', trainConcrete33)
const warehouseFrr33 = require('./routes/batawy1Projects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr33)
const warehouseMataf33 = require('./routes/batawy1Projects/WarehouseMataf')
app.use('/', warehouseMataf33)
const warehouseShameya33 = require('./routes/batawy1Projects/WarehouseShameya')
app.use('/', warehouseShameya33)
const zakzoki33 = require('./routes/batawy1Projects/ZakzokiFireFighting')
app.use('/', zakzoki33)
const metalsaudidecoration33 = require('./routes/batawy1Projects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration33)
const invoiceReport33 = require('./routes/batawy1Projects/InvoiceReport')
app.use('/', invoiceReport33)
//////////////////////////////////////////// Batawy1 
//////////////////////////////////////////// SafaMashaer
const abrajkudai34 = require('./routes/safaMashaerProjects/AbrajKudai')
app.use('/', abrajkudai34)
const alameiaAhla34 = require('./routes/safaMashaerProjects/AlameiaAhla')
app.use('/', alameiaAhla34)
const alameiaConsums34 = require('./routes/safaMashaerProjects/alameiaconsums')
app.use('/', alameiaConsums34)
const alameiaMaintainence34 = require('./routes/safaMashaerProjects/alameiamaintainence')
app.use('/', alameiaMaintainence34)
const campsEmployee34 = require('./routes/safaMashaerProjects/CampsEmployee')
app.use('/', campsEmployee34)
const centralStation34 = require('./routes/safaMashaerProjects/centralStation')
app.use('/', centralStation34)
const enma34 = require('./routes/safaMashaerProjects/Enma')
app.use('/', enma34)
const eamarMaterial34 = require('./routes/safaMashaerProjects/EamarMaterial')
app.use('/', eamarMaterial34)
const firstRingRoad34 = require('./routes/safaMashaerProjects/FirstRingRoad')
app.use('/', firstRingRoad34)
const hrServices34 = require('./routes/safaMashaerProjects/Hrservices')
app.use('/', hrServices34)
const iblik34 = require('./routes/safaMashaerProjects/Iblik')
app.use('/', iblik34)
const infraStracture34 = require('./routes/safaMashaerProjects/InfraStractureHaram')
app.use('/', infraStracture34)
const marwa34 = require('./routes/safaMashaerProjects/Marwa')
app.use('/', marwa34)
const masar34 = require('./routes/safaMashaerProjects/Masar')
app.use('/', masar34)
const mataf34 = require('./routes/safaMashaerProjects/Mataf')
app.use('/', mataf34)
const najm34 = require('./routes/safaMashaerProjects/Najm')
app.use('/', najm34)
const sahat34 = require('./routes/safaMashaerProjects/Sahat')
app.use('/', sahat34)
const salama34 = require('./routes/safaMashaerProjects/Salama')
app.use('/', salama34)
const securityBuildings34 = require('./routes/safaMashaerProjects/SecurityBuildings')
app.use('/', securityBuildings34)
const serviceBuildings34 = require('./routes/safaMashaerProjects/ServiceBuildings')
app.use('/', serviceBuildings34)
const serviceBuildingsSec1634 = require('./routes/safaMashaerProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1634)
const shameya34 = require('./routes/safaMashaerProjects/Shameya')
app.use('/', shameya34)
const trainConcrete34 = require('./routes/safaMashaerProjects/TrainConcrete')
app.use('/', trainConcrete34)
const warehouseFrr34 = require('./routes/safaMashaerProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr34)
const warehouseMataf34 = require('./routes/safaMashaerProjects/WarehouseMataf')
app.use('/', warehouseMataf34)
const warehouseShameya34 = require('./routes/safaMashaerProjects/WarehouseShameya')
app.use('/', warehouseShameya34)
const zakzoki34 = require('./routes/safaMashaerProjects/ZakzokiFireFighting')
app.use('/', zakzoki34)
const metalsaudidecoration34 = require('./routes/safaMashaerProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration34)
const invoiceReport34 = require('./routes/safaMashaerProjects/InvoiceReport')
app.use('/', invoiceReport34)
//////////////////////////////////////////// SafaMashaer 
//////////////////////////////////////////// Matrafy
const abrajkudai35 = require('./routes/matrafyProjects/AbrajKudai')
app.use('/', abrajkudai35)
const alameiaAhla35 = require('./routes/matrafyProjects/AlameiaAhla')
app.use('/', alameiaAhla35)
const alameiaConsums35 = require('./routes/matrafyProjects/alameiaconsums')
app.use('/', alameiaConsums35)
const alameiaMaintainence35 = require('./routes/matrafyProjects/alameiamaintainence')
app.use('/', alameiaMaintainence35)
const campsEmployee35 = require('./routes/matrafyProjects/CampsEmployee')
app.use('/', campsEmployee35)
const centralStation35 = require('./routes/matrafyProjects/centralStation')
app.use('/', centralStation35)
const enma35 = require('./routes/matrafyProjects/Enma')
app.use('/', enma35)
const eamarMaterial35 = require('./routes/matrafyProjects/EamarMaterial')
app.use('/', eamarMaterial35)
const firstRingRoad35 = require('./routes/matrafyProjects/FirstRingRoad')
app.use('/', firstRingRoad35)
const hrServices35 = require('./routes/matrafyProjects/Hrservices')
app.use('/', hrServices35)
const iblik35 = require('./routes/matrafyProjects/Iblik')
app.use('/', iblik35)
const infraStracture35 = require('./routes/matrafyProjects/InfraStractureHaram')
app.use('/', infraStracture35)
const marwa35 = require('./routes/matrafyProjects/Marwa')
app.use('/', marwa35)
const masar35 = require('./routes/matrafyProjects/Masar')
app.use('/', masar35)
const mataf35 = require('./routes/matrafyProjects/Mataf')
app.use('/', mataf35)
const najm35 = require('./routes/matrafyProjects/Najm')
app.use('/', najm35)
const sahat35 = require('./routes/matrafyProjects/Sahat')
app.use('/', sahat35)
const salama35 = require('./routes/matrafyProjects/Salama')
app.use('/', salama35)
const securityBuildings35 = require('./routes/matrafyProjects/SecurityBuildings')
app.use('/', securityBuildings35)
const serviceBuildings35 = require('./routes/matrafyProjects/ServiceBuildings')
app.use('/', serviceBuildings35)
const serviceBuildingsSec1635 = require('./routes/matrafyProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1635)
const shameya35 = require('./routes/matrafyProjects/Shameya')
app.use('/', shameya35)
const trainConcrete35 = require('./routes/matrafyProjects/TrainConcrete')
app.use('/', trainConcrete35)
const warehouseFrr35 = require('./routes/matrafyProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr35)
const warehouseMataf35 = require('./routes/matrafyProjects/WarehouseMataf')
app.use('/', warehouseMataf35)
const warehouseShameya35 = require('./routes/matrafyProjects/WarehouseShameya')
app.use('/', warehouseShameya35)
const zakzoki35 = require('./routes/matrafyProjects/ZakzokiFireFighting')
app.use('/', zakzoki35)
const metalsaudidecoration35 = require('./routes/matrafyProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration35)
const invoiceReport35 = require('./routes/matrafyProjects/InvoiceReport')
app.use('/', invoiceReport35)
//////////////////////////////////////////// Matrafy 
//////////////////////////////////////////// Saqaf
const abrajkudai36 = require('./routes/saqafProjects/AbrajKudai')
app.use('/', abrajkudai36)
const alameiaAhla36 = require('./routes/saqafProjects/AlameiaAhla')
app.use('/', alameiaAhla36)
const alameiaConsums36 = require('./routes/saqafProjects/alameiaconsums')
app.use('/', alameiaConsums36)
const alameiaMaintainence36 = require('./routes/saqafProjects/alameiamaintainence')
app.use('/', alameiaMaintainence36)
const campsEmployee36 = require('./routes/saqafProjects/CampsEmployee')
app.use('/', campsEmployee36)
const centralStation36 = require('./routes/saqafProjects/centralStation')
app.use('/', centralStation36)
const enma36 = require('./routes/saqafProjects/Enma')
app.use('/', enma36)
const eamarMaterial36 = require('./routes/saqafProjects/EamarMaterial')
app.use('/', eamarMaterial36)
const firstRingRoad36 = require('./routes/saqafProjects/FirstRingRoad')
app.use('/', firstRingRoad36)
const hrServices36 = require('./routes/saqafProjects/Hrservices')
app.use('/', hrServices36)
const iblik36 = require('./routes/saqafProjects/Iblik')
app.use('/', iblik36)
const infraStracture36 = require('./routes/saqafProjects/InfraStractureHaram')
app.use('/', infraStracture36)
const marwa36 = require('./routes/saqafProjects/Marwa')
app.use('/', marwa36)
const masar36 = require('./routes/saqafProjects/Masar')
app.use('/', masar36)
const mataf36 = require('./routes/saqafProjects/Mataf')
app.use('/', mataf36)
const najm36 = require('./routes/saqafProjects/Najm')
app.use('/', najm36)
const sahat36 = require('./routes/saqafProjects/Sahat')
app.use('/', sahat36)
const salama36 = require('./routes/saqafProjects/Salama')
app.use('/', salama36)
const securityBuildings36 = require('./routes/saqafProjects/SecurityBuildings')
app.use('/', securityBuildings36)
const serviceBuildings36 = require('./routes/saqafProjects/ServiceBuildings')
app.use('/', serviceBuildings36)
const serviceBuildingsSec1636 = require('./routes/saqafProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1636)
const shameya36 = require('./routes/saqafProjects/Shameya')
app.use('/', shameya36)
const trainConcrete36 = require('./routes/saqafProjects/TrainConcrete')
app.use('/', trainConcrete36)
const warehouseFrr36 = require('./routes/saqafProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr36)
const warehouseMataf36 = require('./routes/saqafProjects/WarehouseMataf')
app.use('/', warehouseMataf36)
const warehouseShameya36 = require('./routes/saqafProjects/WarehouseShameya')
app.use('/', warehouseShameya36)
const zakzoki36 = require('./routes/saqafProjects/ZakzokiFireFighting')
app.use('/', zakzoki36)
const metalsaudidecoration36 = require('./routes/saqafProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration36)
const invoiceReport36 = require('./routes/saqafProjects/InvoiceReport')
app.use('/', invoiceReport36)
//////////////////////////////////////////// Saqaf 
//////////////////////////////////////////// Feda
const abrajkudai37 = require('./routes/fedaProjects/AbrajKudai')
app.use('/', abrajkudai37)
const alameiaAhla37 = require('./routes/fedaProjects/AlameiaAhla')
app.use('/', alameiaAhla37)
const alameiaConsums37 = require('./routes/fedaProjects/alameiaconsums')
app.use('/', alameiaConsums37)
const alameiaMaintainence37 = require('./routes/fedaProjects/alameiamaintainence')
app.use('/', alameiaMaintainence37)
const campsEmployee37 = require('./routes/fedaProjects/CampsEmployee')
app.use('/', campsEmployee37)
const centralStation37 = require('./routes/fedaProjects/centralStation')
app.use('/', centralStation37)
const enma37 = require('./routes/fedaProjects/Enma')
app.use('/', enma37)
const eamarMaterial37 = require('./routes/fedaProjects/EamarMaterial')
app.use('/', eamarMaterial37)
const firstRingRoad37 = require('./routes/fedaProjects/FirstRingRoad')
app.use('/', firstRingRoad37)
const hrServices37 = require('./routes/fedaProjects/Hrservices')
app.use('/', hrServices37)
const iblik37 = require('./routes/fedaProjects/Iblik')
app.use('/', iblik37)
const infraStracture37 = require('./routes/fedaProjects/InfraStractureHaram')
app.use('/', infraStracture37)
const marwa37 = require('./routes/fedaProjects/Marwa')
app.use('/', marwa37)
const masar37 = require('./routes/fedaProjects/Masar')
app.use('/', masar37)
const mataf37 = require('./routes/fedaProjects/Mataf')
app.use('/', mataf37)
const najm37 = require('./routes/fedaProjects/Najm')
app.use('/', najm37)
const sahat37 = require('./routes/fedaProjects/Sahat')
app.use('/', sahat37)
const salama37 = require('./routes/fedaProjects/Salama')
app.use('/', salama37)
const securityBuildings37 = require('./routes/fedaProjects/SecurityBuildings')
app.use('/', securityBuildings37)
const serviceBuildings37 = require('./routes/fedaProjects/ServiceBuildings')
app.use('/', serviceBuildings37)
const serviceBuildingsSec1637 = require('./routes/fedaProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1637)
const shameya37 = require('./routes/fedaProjects/Shameya')
app.use('/', shameya37)
const trainConcrete37 = require('./routes/fedaProjects/TrainConcrete')
app.use('/', trainConcrete37)
const warehouseFrr37 = require('./routes/fedaProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr37)
const warehouseMataf37 = require('./routes/fedaProjects/WarehouseMataf')
app.use('/', warehouseMataf37)
const warehouseShameya37 = require('./routes/fedaProjects/WarehouseShameya')
app.use('/', warehouseShameya37)
const zakzoki37 = require('./routes/fedaProjects/ZakzokiFireFighting')
app.use('/', zakzoki37)
const metalsaudidecoration37 = require('./routes/fedaProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration37)
const invoiceReport37 = require('./routes/fedaProjects/InvoiceReport')
app.use('/', invoiceReport37)
//////////////////////////////////////////// Feda 
//////////////////////////////////////////// Rahmaneya
const abrajkudai38 = require('./routes/rahmaneyaProjects/AbrajKudai')
app.use('/', abrajkudai38)
const alameiaAhla38 = require('./routes/rahmaneyaProjects/AlameiaAhla')
app.use('/', alameiaAhla38)
const alameiaConsums38 = require('./routes/rahmaneyaProjects/alameiaconsums')
app.use('/', alameiaConsums38)
const alameiaMaintainence38 = require('./routes/rahmaneyaProjects/alameiamaintainence')
app.use('/', alameiaMaintainence38)
const campsEmployee38 = require('./routes/rahmaneyaProjects/CampsEmployee')
app.use('/', campsEmployee38)
const centralStation38 = require('./routes/rahmaneyaProjects/centralStation')
app.use('/', centralStation38)
const enma38 = require('./routes/rahmaneyaProjects/Enma')
app.use('/', enma38)
const eamarMaterial38 = require('./routes/rahmaneyaProjects/EamarMaterial')
app.use('/', eamarMaterial38)
const firstRingRoad38 = require('./routes/rahmaneyaProjects/FirstRingRoad')
app.use('/', firstRingRoad38)
const hrServices38 = require('./routes/rahmaneyaProjects/Hrservices')
app.use('/', hrServices38)
const iblik38 = require('./routes/rahmaneyaProjects/Iblik')
app.use('/', iblik38)
const infraStracture38 = require('./routes/rahmaneyaProjects/InfraStractureHaram')
app.use('/', infraStracture38)
const marwa38 = require('./routes/rahmaneyaProjects/Marwa')
app.use('/', marwa38)
const masar38 = require('./routes/rahmaneyaProjects/Masar')
app.use('/', masar38)
const mataf38 = require('./routes/rahmaneyaProjects/Mataf')
app.use('/', mataf38)
const najm38 = require('./routes/rahmaneyaProjects/Najm')
app.use('/', najm38)
const sahat38 = require('./routes/rahmaneyaProjects/Sahat')
app.use('/', sahat38)
const salama38 = require('./routes/rahmaneyaProjects/Salama')
app.use('/', salama38)
const securityBuildings38 = require('./routes/rahmaneyaProjects/SecurityBuildings')
app.use('/', securityBuildings38)
const serviceBuildings38 = require('./routes/rahmaneyaProjects/ServiceBuildings')
app.use('/', serviceBuildings38)
const serviceBuildingsSec1638 = require('./routes/rahmaneyaProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1638)
const shameya38 = require('./routes/rahmaneyaProjects/Shameya')
app.use('/', shameya38)
const trainConcrete38 = require('./routes/rahmaneyaProjects/TrainConcrete')
app.use('/', trainConcrete38)
const warehouseFrr38 = require('./routes/rahmaneyaProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr38)
const warehouseMataf38 = require('./routes/rahmaneyaProjects/WarehouseMataf')
app.use('/', warehouseMataf38)
const warehouseShameya38 = require('./routes/rahmaneyaProjects/WarehouseShameya')
app.use('/', warehouseShameya38)
const zakzoki38 = require('./routes/rahmaneyaProjects/ZakzokiFireFighting')
app.use('/', zakzoki38)
const metalsaudidecoration38 = require('./routes/rahmaneyaProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration38)
const invoiceReport38 = require('./routes/rahmaneyaProjects/InvoiceReport')
app.use('/', invoiceReport38)
//////////////////////////////////////////// Rahmaneya 
//////////////////////////////////////////// Elsalam
const abrajkudai39 = require('./routes/elsalamProjects/AbrajKudai')
app.use('/', abrajkudai39)
const alameiaAhla39 = require('./routes/elsalamProjects/AlameiaAhla')
app.use('/', alameiaAhla39)
const alameiaConsums39 = require('./routes/elsalamProjects/alameiaconsums')
app.use('/', alameiaConsums39)
const alameiaMaintainence39 = require('./routes/elsalamProjects/alameiamaintainence')
app.use('/', alameiaMaintainence39)
const campsEmployee39 = require('./routes/elsalamProjects/CampsEmployee')
app.use('/', campsEmployee39)
const centralStation39 = require('./routes/elsalamProjects/centralStation')
app.use('/', centralStation39)
const enma39 = require('./routes/elsalamProjects/Enma')
app.use('/', enma39)
const eamarMaterial39 = require('./routes/elsalamProjects/EamarMaterial')
app.use('/', eamarMaterial39)
const firstRingRoad39 = require('./routes/elsalamProjects/FirstRingRoad')
app.use('/', firstRingRoad39)
const hrServices39 = require('./routes/elsalamProjects/Hrservices')
app.use('/', hrServices39)
const iblik39 = require('./routes/elsalamProjects/Iblik')
app.use('/', iblik39)
const infraStracture39 = require('./routes/elsalamProjects/InfraStractureHaram')
app.use('/', infraStracture39)
const marwa39 = require('./routes/elsalamProjects/Marwa')
app.use('/', marwa39)
const masar39 = require('./routes/elsalamProjects/Masar')
app.use('/', masar39)
const mataf39 = require('./routes/elsalamProjects/Mataf')
app.use('/', mataf39)
const najm39 = require('./routes/elsalamProjects/Najm')
app.use('/', najm39)
const sahat39 = require('./routes/elsalamProjects/Sahat')
app.use('/', sahat39)
const salama39 = require('./routes/elsalamProjects/Salama')
app.use('/', salama39)
const securityBuildings39 = require('./routes/elsalamProjects/SecurityBuildings')
app.use('/', securityBuildings39)
const serviceBuildings39 = require('./routes/elsalamProjects/ServiceBuildings')
app.use('/', serviceBuildings39)
const serviceBuildingsSec1639 = require('./routes/elsalamProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec1639)
const shameya39 = require('./routes/elsalamProjects/Shameya')
app.use('/', shameya39)
const trainConcrete39 = require('./routes/elsalamProjects/TrainConcrete')
app.use('/', trainConcrete39)
const warehouseFrr39 = require('./routes/elsalamProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr39)
const warehouseMataf39 = require('./routes/elsalamProjects/WarehouseMataf')
app.use('/', warehouseMataf39)
const warehouseShameya39 = require('./routes/elsalamProjects/WarehouseShameya')
app.use('/', warehouseShameya39)
const zakzoki39 = require('./routes/elsalamProjects/ZakzokiFireFighting')
app.use('/', zakzoki39)
const metalsaudidecoration39 = require('./routes/elsalamProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration39)
const invoiceReport39 = require('./routes/elsalamProjects/InvoiceReport')
app.use('/', invoiceReport39)
//////////////////////////////////////////// Elsalam 
//////////////////////////////////////////// Elfateh
const abrajkudai310 = require('./routes/elfatehProjects/AbrajKudai')
app.use('/', abrajkudai310)
const alameiaAhla310 = require('./routes/elfatehProjects/AlameiaAhla')
app.use('/', alameiaAhla310)
const alameiaConsums310 = require('./routes/elfatehProjects/alameiaconsums')
app.use('/', alameiaConsums310)
const alameiaMaintainence310 = require('./routes/elfatehProjects/alameiamaintainence')
app.use('/', alameiaMaintainence310)
const campsEmployee310 = require('./routes/elfatehProjects/CampsEmployee')
app.use('/', campsEmployee310)
const centralStation310 = require('./routes/elfatehProjects/centralStation')
app.use('/', centralStation310)
const enma310 = require('./routes/elfatehProjects/Enma')
app.use('/', enma310)
const eamarMaterial310 = require('./routes/elfatehProjects/EamarMaterial')
app.use('/', eamarMaterial310)
const firstRingRoad310 = require('./routes/elfatehProjects/FirstRingRoad')
app.use('/', firstRingRoad310)
const hrServices310 = require('./routes/elfatehProjects/Hrservices')
app.use('/', hrServices310)
const iblik310 = require('./routes/elfatehProjects/Iblik')
app.use('/', iblik310)
const infraStracture310 = require('./routes/elfatehProjects/InfraStractureHaram')
app.use('/', infraStracture310)
const marwa310 = require('./routes/elfatehProjects/Marwa')
app.use('/', marwa310)
const masar310 = require('./routes/elfatehProjects/Masar')
app.use('/', masar310)
const mataf310 = require('./routes/elfatehProjects/Mataf')
app.use('/', mataf310)
const najm310 = require('./routes/elfatehProjects/Najm')
app.use('/', najm310)
const sahat310 = require('./routes/elfatehProjects/Sahat')
app.use('/', sahat310)
const salama310 = require('./routes/elfatehProjects/Salama')
app.use('/', salama310)
const securityBuildings310 = require('./routes/elfatehProjects/SecurityBuildings')
app.use('/', securityBuildings310)
const serviceBuildings310 = require('./routes/elfatehProjects/ServiceBuildings')
app.use('/', serviceBuildings310)
const serviceBuildingsSec16310 = require('./routes/elfatehProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16310)
const shameya310 = require('./routes/elfatehProjects/Shameya')
app.use('/', shameya310)
const trainConcrete310 = require('./routes/elfatehProjects/TrainConcrete')
app.use('/', trainConcrete310)
const warehouseFrr310 = require('./routes/elfatehProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr310)
const warehouseMataf310 = require('./routes/elfatehProjects/WarehouseMataf')
app.use('/', warehouseMataf310)
const warehouseShameya310 = require('./routes/elfatehProjects/WarehouseShameya')
app.use('/', warehouseShameya310)
const zakzoki310 = require('./routes/elfatehProjects/ZakzokiFireFighting')
app.use('/', zakzoki310)
const metalsaudidecoration310 = require('./routes/elfatehProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration310)
const invoiceReport310 = require('./routes/elfatehProjects/InvoiceReport')
app.use('/', invoiceReport310)
//////////////////////////////////////////// Elfateh 
//////////////////////////////////////////// Paradise
const abrajkudai311 = require('./routes/paradiseProjects/AbrajKudai')
app.use('/', abrajkudai311)
const alameiaAhla311 = require('./routes/paradiseProjects/AlameiaAhla')
app.use('/', alameiaAhla311)
const alameiaConsums311 = require('./routes/paradiseProjects/alameiaconsums')
app.use('/', alameiaConsums311)
const alameiaMaintainence311 = require('./routes/paradiseProjects/alameiamaintainence')
app.use('/', alameiaMaintainence311)
const campsEmployee311 = require('./routes/paradiseProjects/CampsEmployee')
app.use('/', campsEmployee311)
const centralStation311 = require('./routes/paradiseProjects/centralStation')
app.use('/', centralStation311)
const enma311 = require('./routes/paradiseProjects/Enma')
app.use('/', enma311)
const eamarMaterial311 = require('./routes/paradiseProjects/EamarMaterial')
app.use('/', eamarMaterial311)
const firstRingRoad311 = require('./routes/paradiseProjects/FirstRingRoad')
app.use('/', firstRingRoad311)
const hrServices311 = require('./routes/paradiseProjects/Hrservices')
app.use('/', hrServices311)
const iblik311 = require('./routes/paradiseProjects/Iblik')
app.use('/', iblik311)
const infraStracture311 = require('./routes/paradiseProjects/InfraStractureHaram')
app.use('/', infraStracture311)
const marwa311 = require('./routes/paradiseProjects/Marwa')
app.use('/', marwa311)
const masar311 = require('./routes/paradiseProjects/Masar')
app.use('/', masar311)
const mataf311 = require('./routes/paradiseProjects/Mataf')
app.use('/', mataf311)
const najm311 = require('./routes/paradiseProjects/Najm')
app.use('/', najm311)
const sahat311 = require('./routes/paradiseProjects/Sahat')
app.use('/', sahat311)
const salama311 = require('./routes/paradiseProjects/Salama')
app.use('/', salama311)
const securityBuildings311 = require('./routes/paradiseProjects/SecurityBuildings')
app.use('/', securityBuildings311)
const serviceBuildings311 = require('./routes/paradiseProjects/ServiceBuildings')
app.use('/', serviceBuildings311)
const serviceBuildingsSec16311 = require('./routes/paradiseProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16311)
const shameya311 = require('./routes/paradiseProjects/Shameya')
app.use('/', shameya311)
const trainConcrete311 = require('./routes/paradiseProjects/TrainConcrete')
app.use('/', trainConcrete311)
const warehouseFrr311 = require('./routes/paradiseProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr311)
const warehouseMataf311 = require('./routes/paradiseProjects/WarehouseMataf')
app.use('/', warehouseMataf311)
const warehouseShameya311 = require('./routes/paradiseProjects/WarehouseShameya')
app.use('/', warehouseShameya311)
const zakzoki311 = require('./routes/paradiseProjects/ZakzokiFireFighting')
app.use('/', zakzoki311)
const metalsaudidecoration311 = require('./routes/paradiseProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration311)
const invoiceReport311 = require('./routes/paradiseProjects/InvoiceReport')
app.use('/', invoiceReport311)
//////////////////////////////////////////// Paradise 
//////////////////////////////////////////// Batawy2
const abrajkudai312 = require('./routes/batawy2Projects/AbrajKudai')
app.use('/', abrajkudai312)
const alameiaAhla312 = require('./routes/batawy2Projects/AlameiaAhla')
app.use('/', alameiaAhla312)
const alameiaConsums312 = require('./routes/batawy2Projects/alameiaconsums')
app.use('/', alameiaConsums312)
const alameiaMaintainence312 = require('./routes/batawy2Projects/alameiamaintainence')
app.use('/', alameiaMaintainence312)
const campsEmployee312 = require('./routes/batawy2Projects/CampsEmployee')
app.use('/', campsEmployee312)
const centralStation312 = require('./routes/batawy2Projects/centralStation')
app.use('/', centralStation312)
const enma312 = require('./routes/batawy2Projects/Enma')
app.use('/', enma312)
const eamarMaterial312 = require('./routes/batawy2Projects/EamarMaterial')
app.use('/', eamarMaterial312)
const firstRingRoad312 = require('./routes/batawy2Projects/FirstRingRoad')
app.use('/', firstRingRoad312)
const hrServices312 = require('./routes/batawy2Projects/Hrservices')
app.use('/', hrServices312)
const iblik312 = require('./routes/batawy2Projects/Iblik')
app.use('/', iblik312)
const infraStracture312 = require('./routes/batawy2Projects/InfraStractureHaram')
app.use('/', infraStracture312)
const marwa312 = require('./routes/batawy2Projects/Marwa')
app.use('/', marwa312)
const masar312 = require('./routes/batawy2Projects/Masar')
app.use('/', masar312)
const mataf312 = require('./routes/batawy2Projects/Mataf')
app.use('/', mataf312)
const najm312 = require('./routes/batawy2Projects/Najm')
app.use('/', najm312)
const sahat312 = require('./routes/batawy2Projects/Sahat')
app.use('/', sahat312)
const salama312 = require('./routes/batawy2Projects/Salama')
app.use('/', salama312)
const securityBuildings312 = require('./routes/batawy2Projects/SecurityBuildings')
app.use('/', securityBuildings312)
const serviceBuildings312 = require('./routes/batawy2Projects/ServiceBuildings')
app.use('/', serviceBuildings312)
const serviceBuildingsSec16312 = require('./routes/batawy2Projects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16312)
const shameya312 = require('./routes/batawy2Projects/Shameya')
app.use('/', shameya312)
const trainConcrete312 = require('./routes/batawy2Projects/TrainConcrete')
app.use('/', trainConcrete312)
const warehouseFrr312 = require('./routes/batawy2Projects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr312)
const warehouseMataf312 = require('./routes/batawy2Projects/WarehouseMataf')
app.use('/', warehouseMataf312)
const warehouseShameya312 = require('./routes/batawy2Projects/WarehouseShameya')
app.use('/', warehouseShameya312)
const zakzoki312 = require('./routes/batawy2Projects/ZakzokiFireFighting')
app.use('/', zakzoki312)
const metalsaudidecoration312 = require('./routes/batawy2Projects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration312)
const invoiceReport312 = require('./routes/batawy2Projects/InvoiceReport')
app.use('/', invoiceReport312)
//////////////////////////////////////////// Batawy2 
//////////////////////////////////////////// Hemyani
const abrajkudai313 = require('./routes/hemyaniProjects/AbrajKudai')
app.use('/', abrajkudai313)
const alameiaAhla313 = require('./routes/hemyaniProjects/AlameiaAhla')
app.use('/', alameiaAhla313)
const alameiaConsums313 = require('./routes/hemyaniProjects/alameiaconsums')
app.use('/', alameiaConsums313)
const alameiaMaintainence313 = require('./routes/hemyaniProjects/alameiamaintainence')
app.use('/', alameiaMaintainence313)
const campsEmployee313 = require('./routes/hemyaniProjects/CampsEmployee')
app.use('/', campsEmployee313)
const centralStation313 = require('./routes/hemyaniProjects/centralStation')
app.use('/', centralStation313)
const enma313 = require('./routes/hemyaniProjects/Enma')
app.use('/', enma313)
const eamarMaterial313 = require('./routes/hemyaniProjects/EamarMaterial')
app.use('/', eamarMaterial313)
const firstRingRoad313 = require('./routes/hemyaniProjects/FirstRingRoad')
app.use('/', firstRingRoad313)
const hrServices313 = require('./routes/hemyaniProjects/Hrservices')
app.use('/', hrServices313)
const iblik313 = require('./routes/hemyaniProjects/Iblik')
app.use('/', iblik313)
const infraStracture313 = require('./routes/hemyaniProjects/InfraStractureHaram')
app.use('/', infraStracture313)
const marwa313 = require('./routes/hemyaniProjects/Marwa')
app.use('/', marwa313)
const masar313 = require('./routes/hemyaniProjects/Masar')
app.use('/', masar313)
const mataf313 = require('./routes/hemyaniProjects/Mataf')
app.use('/', mataf313)
const najm313 = require('./routes/hemyaniProjects/Najm')
app.use('/', najm313)
const sahat313 = require('./routes/hemyaniProjects/Sahat')
app.use('/', sahat313)
const salama313 = require('./routes/hemyaniProjects/Salama')
app.use('/', salama313)
const securityBuildings313 = require('./routes/hemyaniProjects/SecurityBuildings')
app.use('/', securityBuildings313)
const serviceBuildings313 = require('./routes/hemyaniProjects/ServiceBuildings')
app.use('/', serviceBuildings313)
const serviceBuildingsSec16313 = require('./routes/hemyaniProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16313)
const shameya313 = require('./routes/hemyaniProjects/Shameya')
app.use('/', shameya313)
const trainConcrete313 = require('./routes/hemyaniProjects/TrainConcrete')
app.use('/', trainConcrete313)
const warehouseFrr313 = require('./routes/hemyaniProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr313)
const warehouseMataf313 = require('./routes/hemyaniProjects/WarehouseMataf')
app.use('/', warehouseMataf313)
const warehouseShameya313 = require('./routes/hemyaniProjects/WarehouseShameya')
app.use('/', warehouseShameya313)
const zakzoki313 = require('./routes/hemyaniProjects/ZakzokiFireFighting')
app.use('/', zakzoki313)
const metalsaudidecoration313 = require('./routes/hemyaniProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration313)
const invoiceReport313 = require('./routes/hemyaniProjects/InvoiceReport')
app.use('/', invoiceReport313)
//////////////////////////////////////////// Hemyani 
//////////////////////////////////////////// Nefeay
const abrajkudai314 = require('./routes/nefeayProjects/AbrajKudai')
app.use('/', abrajkudai314)
const alameiaAhla314 = require('./routes/nefeayProjects/AlameiaAhla')
app.use('/', alameiaAhla314)
const alameiaConsums314 = require('./routes/nefeayProjects/alameiaconsums')
app.use('/', alameiaConsums314)
const alameiaMaintainence314 = require('./routes/nefeayProjects/alameiamaintainence')
app.use('/', alameiaMaintainence314)
const campsEmployee314 = require('./routes/nefeayProjects/CampsEmployee')
app.use('/', campsEmployee314)
const centralStation314 = require('./routes/nefeayProjects/centralStation')
app.use('/', centralStation314)
const enma314 = require('./routes/nefeayProjects/Enma')
app.use('/', enma314)
const eamarMaterial314 = require('./routes/nefeayProjects/EamarMaterial')
app.use('/', eamarMaterial314)
const firstRingRoad314 = require('./routes/nefeayProjects/FirstRingRoad')
app.use('/', firstRingRoad314)
const hrServices314 = require('./routes/nefeayProjects/Hrservices')
app.use('/', hrServices314)
const iblik314 = require('./routes/nefeayProjects/Iblik')
app.use('/', iblik314)
const infraStracture314 = require('./routes/nefeayProjects/InfraStractureHaram')
app.use('/', infraStracture314)
const marwa314 = require('./routes/nefeayProjects/Marwa')
app.use('/', marwa314)
const masar314 = require('./routes/nefeayProjects/Masar')
app.use('/', masar314)
const mataf314 = require('./routes/nefeayProjects/Mataf')
app.use('/', mataf314)
const najm314 = require('./routes/nefeayProjects/Najm')
app.use('/', najm314)
const sahat314 = require('./routes/nefeayProjects/Sahat')
app.use('/', sahat314)
const salama314 = require('./routes/nefeayProjects/Salama')
app.use('/', salama314)
const securityBuildings314 = require('./routes/nefeayProjects/SecurityBuildings')
app.use('/', securityBuildings314)
const serviceBuildings314 = require('./routes/nefeayProjects/ServiceBuildings')
app.use('/', serviceBuildings314)
const serviceBuildingsSec16314 = require('./routes/nefeayProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16314)
const shameya314 = require('./routes/nefeayProjects/Shameya')
app.use('/', shameya314)
const trainConcrete314 = require('./routes/nefeayProjects/TrainConcrete')
app.use('/', trainConcrete314)
const warehouseFrr314 = require('./routes/nefeayProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr314)
const warehouseMataf314 = require('./routes/nefeayProjects/WarehouseMataf')
app.use('/', warehouseMataf314)
const warehouseShameya314 = require('./routes/nefeayProjects/WarehouseShameya')
app.use('/', warehouseShameya314)
const zakzoki314 = require('./routes/nefeayProjects/ZakzokiFireFighting')
app.use('/', zakzoki314)
const metalsaudidecoration314 = require('./routes/nefeayProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration314)
const invoiceReport314 = require('./routes/nefeayProjects/InvoiceReport')
app.use('/', invoiceReport314)
//////////////////////////////////////////// Nefeay 
//////////////////////////////////////////// Morgan1 Nassem
const abrajkudai315 = require('./routes/morgan1NaseemProjects/AbrajKudai')
app.use('/', abrajkudai315)
const alameiaAhla315 = require('./routes/morgan1NaseemProjects/AlameiaAhla')
app.use('/', alameiaAhla315)
const alameiaConsums315 = require('./routes/morgan1NaseemProjects/alameiaconsums')
app.use('/', alameiaConsums315)
const alameiaMaintainence315 = require('./routes/morgan1NaseemProjects/alameiamaintainence')
app.use('/', alameiaMaintainence315)
const campsEmployee315 = require('./routes/morgan1NaseemProjects/CampsEmployee')
app.use('/', campsEmployee315)
const centralStation315 = require('./routes/morgan1NaseemProjects/centralStation')
app.use('/', centralStation315)
const enma315 = require('./routes/morgan1NaseemProjects/Enma')
app.use('/', enma315)
const eamarMaterial315 = require('./routes/morgan1NaseemProjects/EamarMaterial')
app.use('/', eamarMaterial315)
const firstRingRoad315 = require('./routes/morgan1NaseemProjects/FirstRingRoad')
app.use('/', firstRingRoad315)
const hrServices315 = require('./routes/morgan1NaseemProjects/Hrservices')
app.use('/', hrServices315)
const iblik315 = require('./routes/morgan1NaseemProjects/Iblik')
app.use('/', iblik315)
const infraStracture315 = require('./routes/morgan1NaseemProjects/InfraStractureHaram')
app.use('/', infraStracture315)
const marwa315 = require('./routes/morgan1NaseemProjects/Marwa')
app.use('/', marwa315)
const masar315 = require('./routes/morgan1NaseemProjects/Masar')
app.use('/', masar315)
const mataf315 = require('./routes/morgan1NaseemProjects/Mataf')
app.use('/', mataf315)
const najm315 = require('./routes/morgan1NaseemProjects/Najm')
app.use('/', najm315)
const sahat315 = require('./routes/morgan1NaseemProjects/Sahat')
app.use('/', sahat315)
const salama315 = require('./routes/morgan1NaseemProjects/Salama')
app.use('/', salama315)
const securityBuildings315 = require('./routes/morgan1NaseemProjects/SecurityBuildings')
app.use('/', securityBuildings315)
const serviceBuildings315 = require('./routes/morgan1NaseemProjects/ServiceBuildings')
app.use('/', serviceBuildings315)
const serviceBuildingsSec16315 = require('./routes/morgan1NaseemProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16315)
const shameya315 = require('./routes/morgan1NaseemProjects/Shameya')
app.use('/', shameya315)
const trainConcrete315 = require('./routes/morgan1NaseemProjects/TrainConcrete')
app.use('/', trainConcrete315)
const warehouseFrr315 = require('./routes/morgan1NaseemProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr315)
const warehouseMataf315 = require('./routes/morgan1NaseemProjects/WarehouseMataf')
app.use('/', warehouseMataf315)
const warehouseShameya315 = require('./routes/morgan1NaseemProjects/WarehouseShameya')
app.use('/', warehouseShameya315)
const zakzoki315 = require('./routes/morgan1NaseemProjects/ZakzokiFireFighting')
app.use('/', zakzoki315)
const metalsaudidecoration315 = require('./routes/morgan1NaseemProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration315)
const invoiceReport315 = require('./routes/morgan1NaseemProjects/InvoiceReport')
app.use('/', invoiceReport315)
//////////////////////////////////////////// Morgan1 Nassem 
//////////////////////////////////////////// Morgan2 Bathaa
const abrajkudai316 = require('./routes/morgan2BathaaProjects/AbrajKudai')
app.use('/', abrajkudai316)
const alameiaAhla316 = require('./routes/morgan2BathaaProjects/AlameiaAhla')
app.use('/', alameiaAhla316)
const alameiaConsums316 = require('./routes/morgan2BathaaProjects/alameiaconsums')
app.use('/', alameiaConsums316)
const alameiaMaintainence316 = require('./routes/morgan2BathaaProjects/alameiamaintainence')
app.use('/', alameiaMaintainence316)
const campsEmployee316 = require('./routes/morgan2BathaaProjects/CampsEmployee')
app.use('/', campsEmployee316)
const centralStation316 = require('./routes/morgan2BathaaProjects/centralStation')
app.use('/', centralStation316)
const enma316 = require('./routes/morgan2BathaaProjects/Enma')
app.use('/', enma316)
const eamarMaterial316 = require('./routes/morgan2BathaaProjects/EamarMaterial')
app.use('/', eamarMaterial316)
const firstRingRoad316 = require('./routes/morgan2BathaaProjects/FirstRingRoad')
app.use('/', firstRingRoad316)
const hrServices316 = require('./routes/morgan2BathaaProjects/Hrservices')
app.use('/', hrServices316)
const iblik316 = require('./routes/morgan2BathaaProjects/Iblik')
app.use('/', iblik316)
const infraStracture316 = require('./routes/morgan2BathaaProjects/InfraStractureHaram')
app.use('/', infraStracture316)
const marwa316 = require('./routes/morgan2BathaaProjects/Marwa')
app.use('/', marwa316)
const masar316 = require('./routes/morgan2BathaaProjects/Masar')
app.use('/', masar316)
const mataf316 = require('./routes/morgan2BathaaProjects/Mataf')
app.use('/', mataf316)
const najm316 = require('./routes/morgan2BathaaProjects/Najm')
app.use('/', najm316)
const sahat316 = require('./routes/morgan2BathaaProjects/Sahat')
app.use('/', sahat316)
const salama316 = require('./routes/morgan2BathaaProjects/Salama')
app.use('/', salama316)
const securityBuildings316 = require('./routes/morgan2BathaaProjects/SecurityBuildings')
app.use('/', securityBuildings316)
const serviceBuildings316 = require('./routes/morgan2BathaaProjects/ServiceBuildings')
app.use('/', serviceBuildings316)
const serviceBuildingsSec16316 = require('./routes/morgan2BathaaProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16316)
const shameya316 = require('./routes/morgan2BathaaProjects/Shameya')
app.use('/', shameya316)
const trainConcrete316 = require('./routes/morgan2BathaaProjects/TrainConcrete')
app.use('/', trainConcrete316)
const warehouseFrr316 = require('./routes/morgan2BathaaProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr316)
const warehouseMataf316 = require('./routes/morgan2BathaaProjects/WarehouseMataf')
app.use('/', warehouseMataf316)
const warehouseShameya316 = require('./routes/morgan2BathaaProjects/WarehouseShameya')
app.use('/', warehouseShameya316)
const zakzoki316 = require('./routes/morgan2BathaaProjects/ZakzokiFireFighting')
app.use('/', zakzoki316)
const metalsaudidecoration316 = require('./routes/morgan2BathaaProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration316)
const invoiceReport316 = require('./routes/morgan2BathaaProjects/InvoiceReport')
app.use('/', invoiceReport316)
//////////////////////////////////////////// Morgan2 Bathaa 
//////////////////////////////////////////// Waqf
const abrajkudai317 = require('./routes/waqfProjects/AbrajKudai')
app.use('/', abrajkudai317)
const alameiaAhla317 = require('./routes/waqfProjects/AlameiaAhla')
app.use('/', alameiaAhla317)
const alameiaConsums317 = require('./routes/waqfProjects/alameiaconsums')
app.use('/', alameiaConsums317)
const alameiaMaintainence317 = require('./routes/waqfProjects/alameiamaintainence')
app.use('/', alameiaMaintainence317)
const campsEmployee317 = require('./routes/waqfProjects/CampsEmployee')
app.use('/', campsEmployee317)
const centralStation317 = require('./routes/waqfProjects/centralStation')
app.use('/', centralStation317)
const enma317 = require('./routes/waqfProjects/Enma')
app.use('/', enma317)
const eamarMaterial317 = require('./routes/waqfProjects/EamarMaterial')
app.use('/', eamarMaterial317)
const firstRingRoad317 = require('./routes/waqfProjects/FirstRingRoad')
app.use('/', firstRingRoad317)
const hrServices317 = require('./routes/waqfProjects/Hrservices')
app.use('/', hrServices317)
const iblik317 = require('./routes/waqfProjects/Iblik')
app.use('/', iblik317)
const infraStracture317 = require('./routes/waqfProjects/InfraStractureHaram')
app.use('/', infraStracture317)
const marwa317 = require('./routes/waqfProjects/Marwa')
app.use('/', marwa317)
const masar317 = require('./routes/waqfProjects/Masar')
app.use('/', masar317)
const mataf317 = require('./routes/waqfProjects/Mataf')
app.use('/', mataf317)
const najm317 = require('./routes/waqfProjects/Najm')
app.use('/', najm317)
const sahat317 = require('./routes/waqfProjects/Sahat')
app.use('/', sahat317)
const salama317 = require('./routes/waqfProjects/Salama')
app.use('/', salama317)
const securityBuildings317 = require('./routes/waqfProjects/SecurityBuildings')
app.use('/', securityBuildings317)
const serviceBuildings317 = require('./routes/waqfProjects/ServiceBuildings')
app.use('/', serviceBuildings317)
const serviceBuildingsSec16317 = require('./routes/waqfProjects/ServiceBuildingsSec16')
app.use('/', serviceBuildingsSec16317)
const shameya317 = require('./routes/waqfProjects/Shameya')
app.use('/', shameya317)
const trainConcrete317 = require('./routes/waqfProjects/TrainConcrete')
app.use('/', trainConcrete317)
const warehouseFrr317 = require('./routes/waqfProjects/WarehouseFirstRingRoad')
app.use('/', warehouseFrr317)
const warehouseMataf317 = require('./routes/waqfProjects/WarehouseMataf')
app.use('/', warehouseMataf317)
const warehouseShameya317 = require('./routes/waqfProjects/WarehouseShameya')
app.use('/', warehouseShameya317)
const zakzoki317 = require('./routes/waqfProjects/ZakzokiFireFighting')
app.use('/', zakzoki317)
const metalsaudidecoration317 = require('./routes/waqfProjects/MetalSaudiDecoration')
app.use('/', metalsaudidecoration317)
const invoiceReport317 = require('./routes/waqfProjects/InvoiceReport')
app.use('/', invoiceReport317)
//////////////////////////////////////////// Waqf 
///////////////////////////////////////////////////////////// Projects

////////////// Food    
const alameiaFoodExtraRouter = require('./routes/alameiafood')
app.use('/', alameiaFoodExtraRouter)
const haramainFoodExtraRouter = require('./routes/haramainfood')
app.use('/', haramainFoodExtraRouter)
const ewaaaFoodExtraRouter = require('./routes/ewaaafood')
app.use('/', ewaaaFoodExtraRouter)
const ewaabFoodExtraRouter = require('./routes/ewaabfood')
app.use('/', ewaabFoodExtraRouter)
////////////// Food        
/////////////////////Maintainence   
const maintainenceAlameia = require('./routes/Maintainence/Alameia')
app.use('/', maintainenceAlameia)
/////////////////////Maintainence    
///////////// Transport      
const alameiaTransExtraRouter = require('./routes/alameiatrans')
app.use('/', alameiaTransExtraRouter)
const haramainTransExtraRouter = require('./routes/haramaintrans')
app.use('/', haramainTransExtraRouter)
const ewaaaTransExtraRouter = require('./routes/ewaaatrans')
app.use('/', ewaaaTransExtraRouter)
const ewaabTransExtraRouter = require('./routes/ewaabtrans')
app.use('/', ewaabTransExtraRouter)
///////////// Transport
///////////////////////// Vacancies - Excel
const alameiaVacancies = require('./routes/Vacants/alameia')
app.use('/', alameiaVacancies)
const haramainVacancies = require('./routes/Vacants/haramain')
app.use('/', haramainVacancies)
const ewaaaVacancies = require('./routes/Vacants/ewaaa')
app.use('/', ewaaaVacancies)
const ewaabVacancies = require('./routes/Vacants/ewaab')
app.use('/', ewaabVacancies)
const sawady1Vacancies = require('./routes/Vacants/sawady1')
app.use('/', sawady1Vacancies)
const sawady2Vacancies = require('./routes/Vacants/sawady2')
app.use('/', sawady2Vacancies)
const batawy1Vacancies = require('./routes/Vacants/batawy1')
app.use('/', batawy1Vacancies)
const batawy2Vacancies = require('./routes/Vacants/batawy2')
app.use('/', batawy2Vacancies)
const safaMashaerVacancies = require('./routes/Vacants/safaMashaer')
app.use('/', safaMashaerVacancies)
const matrafyVacancies = require('./routes/Vacants/matrafy')
app.use('/', matrafyVacancies)
const morgan1NaseemVacancies = require('./routes/Vacants/morgan1Naseem')
app.use('/', morgan1NaseemVacancies)
const morgan2BathaaVacancies = require('./routes/Vacants/morgan2Bathaa')
app.use('/', morgan2BathaaVacancies)
const fedaVacancies = require('./routes/Vacants/feda')
app.use('/', fedaVacancies)
const saqafVacancies = require('./routes/Vacants/saqaf')
app.use('/', saqafVacancies)
const waqfVacancies = require('./routes/Vacants/waqf')
app.use('/', waqfVacancies)
const hemyaniVacancies = require('./routes/Vacants/hemyani')
app.use('/', hemyaniVacancies)
const rahmaneyaVacancies = require('./routes/Vacants/rahmaneya')
app.use('/', rahmaneyaVacancies)
const elsalamVacancies = require('./routes/Vacants/elsalam')
app.use('/', elsalamVacancies)
const elfatehVacancies = require('./routes/Vacants/elfateh')
app.use('/', elfatehVacancies)
const paradiseVacancies = require('./routes/Vacants/paradise')
app.use('/', paradiseVacancies)
const nefeayVacancies = require('./routes/Vacants/nefeay')
app.use('/', nefeayVacancies)

///////////////////////// Vacancies - Excel


db.sequelize.sync().then(() => {
	app.listen(port, () => {
		console.log(`server running on port : ${port}`);
	});
});

function initial() {
	Role.create({
		id: 1,
		name: "USER"
	});

	Role.create({
		id: 2,
		name: "ADMIN"
	});

	Role.create({
		id: 3,
		name: "PM"
	});
}